### PR TITLE
testing CI -- pull request from fork

### PR DESCRIPTION
**Pull request by wyli**
This is a one-liner dummy description to induce a CI build with a PR edit.

### CODE REVIEW

**Comment by wyli** [comment]
@dzhoshkun so the CI is not running for this PR...

**Comment by dzhoshkun** [comment]
@wyli I've modified the webhook to trigger builds for PRs as well. Could you please:

* [x] add a commit to your fork
* [x] submit another PR

Both of the above events should trigger a build now.

**Review by dzhoshkun — APPROVED** [review]
This is dummy one-liner approval to induce a CI build.

**Comment by wyli** [comment]
added another commit, but it's automatically appended to this PR, therefore I'm closing this and create another PR.

**Pull request closed without merging**
